name: 'PR-Plan'
on:
  pull_request:
    paths:
      - 'terraform/**'
    branches:
      - main
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          terraform:
            - 'terraform/**'
        base: ${{ github.head_ref }}
  test:
    needs: changes
    if: ${{ needs.changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "This is a test only run on a certain condition"
